name = "programmerbar-web"
compatibility_date = "2023-12-01"

compatibility_flags = [ "nodejs_compat" ]

pages_build_output_dir = "./build"

[[r2_buckets]]
binding = "R2"
bucket_name = "profile-pics"

[[kv_namespaces]]
binding = "KV"
id = "6ea7665f68a7445baedeab6d9008263a"
