name = "programmerbar-web"
compatibility_date = "2024-04-14"

compatibility_flags = [ "nodejs_compat" ]

pages_build_output_dir = "./build"

[[kv_namespaces]]
binding = "KV"
id = "6ea7665f68a7445baedeab6d9008263a"
