name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install

      - name: Check style
        run: pnpm run format:check

      - name: Build
        run: pnpm run build

      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: "pnpm"
          command: pages deploy ./dist --project-name=programmerbar-web
