name: Deploy apps

on:
  push:
    branches:
      - main

jobs:
  deploy-web:
    name: Deploy web app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: ./.github/actions/pnpm-install
      - run: pnpm --filter=web run build
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: "pnpm"
          workingDirectory: apps/web
          command: pages deploy .svelte-kit/cloudflare --project-name=programmerbar-web

  deploy-sanity:
    name: Deploy sanity app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install
      - run: pnpm --filter=cms run deploy
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
